version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: zenith
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - .:/app:RO
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
      - storage

  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE="zenith"
      - MYSQL_ROOT_PASSWORD="2z8FDa4zDw4zNh06KemsDyWFOu2lR2FJ"

  storage:
    image: bitnami/minio:latest
    container_name: minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=f1f6LQMWJ0CLsRP7Z1W9P4xg4C0sgCel
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  ws:
    image: quay.io/soketi/soketi:latest-16-alpine
    container_name: ws
    ports:
      - "6001:6001"
      - "9061:9061"
    environment:
      - DEFAULT_APP_ID=7Z1W9P4xg4C0sg
      - DEFAULT_APP_KEY=f1f6LQMWJ0CLsR
      - DEFAULT_APP_SECRET=DyWFOu2lR2FJ6LQMWJ07Z1W

volumes:
  mysql_data:
  minio_data:
