version: "3.8"

services:
  zenith:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zenith
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - .:/app:RO
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mysql
      - minio

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE="zenith"
      - MYSQL_ROOT_PASSWORD="2z8FDa4zDw4zNh06KemsDyWFOu2lR2FJ"

  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=f1f6LQMWJ0CLsRP7Z1W9P4xg4C0sgCel
    command: server /data --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mysql_data:
  minio_data:
